<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Default email templates
    |--------------------------------------------------------------------------
    |
    | These templates are the app defaults for every shop. Each shop can
    | override subject/content and enabled state in the DB.
    |
    | Keys are stable identifiers used in URLs and storage.
    */
    'templates' => [
        'skipped_order' => [
            'name' => 'Skipped Order',
            'type' => 'Order management',
            'icon' => 'order-draft',
            'description' => 'Sends when an order is skipped.',
            'enabled' => true,
            'subject' => 'Order skipped for your subscription!',
            'body_html' => '<p>Hello {{ first_name }} {{ last_name }},</p><p>Your upcoming order for <b>{{ order_date }}</b> was skipped. You will not be charged. Your next subscription charge date is <b>{{ next_order_date }}</b>.</p><p>You can manage the subscription using the button below:</p>',
            'settings' => [
                'showBtn' => true,
                'btnText' => 'Manage Subscription',
                'fullWidth' => false,
                'showItems' => true,
                'qtyTitle' => 'Quantity',
                'showAddresses' => true,
                'shippingTitle' => 'Shipping Address',
                'billingTitle' => 'Billing Address',
                'shippingText' => '{{ shipping_title }}<br>{{ delivery_address.name }}<br>{{ delivery_address.address1 }}<br>{{ delivery_address.address2 }}',
                'billingText' => '{{ billing_address.name }}<br>{{ billing_address.address1 }}<br>{{ billing_address.address2 }}',
                'showOrderDate' => true,
                'orderDateTitle' => 'Next Order Date',
                'paymentTitle' => 'Payment Method',
                'footerText' => '<p>If you have any questions or need assistance, our support team is here to help. Just reply to this email or reach out at {{ merchant_support_email }}</p>',
            ],
        ],
        'unskipped_order' => [
            'name' => 'Unskipped Order',
            'type' => 'Order management',
            'icon' => 'order-draft',
            'description' => 'Sends when a skipped order is unskipped.',
            'enabled' => true,
            'subject' => 'Order unskipped for your subscription!',
            'body_html' => '<p>Hello {{ first_name }} {{ last_name }},</p><p>Your upcoming order for <b>{{ order_date }}</b> is no longer skipped.</p><p>You can manage the subscription using the button below:</p>',
            'settings' => [
                'showBtn' => true,
                'btnText' => 'Manage Subscription',
                'fullWidth' => false,
                'showItems' => true,
                'qtyTitle' => 'Quantity',
                'showAddresses' => true,
                'shippingTitle' => 'Shipping Address',
                'billingTitle' => 'Billing Address',
                'shippingText' => '{{ shipping_title }}<br>{{ delivery_address.name }}<br>{{ delivery_address.address1 }}<br>{{ delivery_address.address2 }}',
                'billingText' => '{{ billing_address.name }}<br>{{ billing_address.address1 }}<br>{{ billing_address.address2 }}',
                'showOrderDate' => true,
                'orderDateTitle' => 'Next Order Date',
                'paymentTitle' => 'Payment Method',
                'footerText' => '<p>If you have any questions or need assistance, our support team is here to help. Just reply to this email or reach out at {{ merchant_support_email }}</p>',
            ],
        ],
        'subscription_created' => [
            'name' => 'Subscription Created',
            'type' => 'Subscription events',
            'icon' => 'credit-card',
            'description' => 'Sends when a new subscription is created.',
            'enabled' => true,
            'subject' => 'Your new subscription confirmed!',
            'body_html' => '<p>Hello {{ first_name }} {{ last_name }},</p><p>Thank you for your subscription purchase!</p><p>Here are your subscription details:</p>',
            'settings' => [
                'showBtn' => true,
                'btnText' => 'Manage Subscription',
                'fullWidth' => false,
                'showItems' => true,
                'qtyTitle' => 'Quantity',
                'showAddresses' => true,
                'shippingTitle' => 'Shipping Address',
                'billingTitle' => 'Billing Address',
                'shippingText' => '{{ shipping_title }}<br>{{ delivery_address.name }}<br>{{ delivery_address.address1 }}<br>{{ delivery_address.address2 }}',
                'billingText' => '{{ billing_address.name }}<br>{{ billing_address.address1 }}<br>{{ billing_address.address2 }}',
                'showOrderDate' => true,
                'orderDateTitle' => 'Next Order Date',
                'paymentTitle' => 'Payment Method',
                'footerText' => '<p>If you have any questions or need assistance, our support team is here to help. Just reply to this email or reach out at {{ merchant_support_email }}</p>',
            ],
        ],
        'subscription_paused' => [
            'name' => 'Subscription Paused',
            'type' => 'Subscription events',
            'icon' => 'credit-card',
            'description' => 'Sends when a subscription is paused.',
            'enabled' => true,
            'subject' => 'Your subscription has been paused!',
            'body_html' => '<p>Hello {{ first_name }} {{ last_name }},</p><p>Your subscription has been paused.</p><p>You can manage the subscription using the button below:</p>',
            'settings' => [
                'showBtn' => true,
                'btnText' => 'Manage Subscription',
                'fullWidth' => false,
                'showItems' => true,
                'qtyTitle' => 'Quantity',
                'showAddresses' => true,
                'shippingTitle' => 'Shipping Address',
                'billingTitle' => 'Billing Address',
                'shippingText' => '{{ shipping_title }}<br>{{ delivery_address.name }}<br>{{ delivery_address.address1 }}<br>{{ delivery_address.address2 }}',
                'billingText' => '{{ billing_address.name }}<br>{{ billing_address.address1 }}<br>{{ billing_address.address2 }}',
                'showOrderDate' => true,
                'orderDateTitle' => 'Next Order Date',
                'paymentTitle' => 'Payment Method',
                'footerText' => '<p>If you have any questions or need assistance, our support team is here to help. Just reply to this email or reach out at {{ merchant_support_email }}</p>',
            ],
        ],
        'subscription_resumed' => [
            'name' => 'Subscription Resumed',
            'type' => 'Subscription events',
            'icon' => 'credit-card',
            'description' => 'Sends when a subscription is resumed.',
            'enabled' => true,
            'subject' => 'Your subscription has resumed',
            'body_html' => '<p>Hello {{ first_name }} {{ last_name }},</p><p>Your subscription has been resumed.</p><p>You can manage the subscription using the button below:</p>',
            'settings' => [
                'showBtn' => true,
                'btnText' => 'Manage Subscription',
                'fullWidth' => false,
                'showItems' => true,
                'qtyTitle' => 'Quantity',
                'showAddresses' => true,
                'shippingTitle' => 'Shipping Address',
                'billingTitle' => 'Billing Address',
                'shippingText' => '{{ shipping_title }}<br>{{ delivery_address.name }}<br>{{ delivery_address.address1 }}<br>{{ delivery_address.address2 }}',
                'billingText' => '{{ billing_address.name }}<br>{{ billing_address.address1 }}<br>{{ billing_address.address2 }}',
                'showOrderDate' => true,
                'orderDateTitle' => 'Next Order Date',
                'paymentTitle' => 'Payment Method',
                'footerText' => '<p>If you have any questions or need assistance, our support team is here to help. Just reply to this email or reach out at {{ merchant_support_email }}</p>',
            ],
        ],
        'subscription_cancelled' => [
            'name' => 'Subscription Cancelled',
            'type' => 'Subscription events',
            'icon' => 'credit-card',
            'description' => 'Sends when a subscription is cancelled.',
            'enabled' => true,
            'subject' => 'Your subscription has been cancelled!',
            'body_html' => '<p>Hello {{ first_name }} {{ last_name }},</p><p>Your subscription has been cancelled.</p><p>You can manage the subscription using the button below:</p>',
            'settings' => [
                'showBtn' => true,
                'btnText' => 'Manage Subscription',
                'fullWidth' => false,
                'showItems' => true,
                'qtyTitle' => 'Quantity',
                'showAddresses' => true,
                'shippingTitle' => 'Shipping Address',
                'billingTitle' => 'Billing Address',
                'shippingText' => '{{ shipping_title }}<br>{{ delivery_address.name }}<br>{{ delivery_address.address1 }}<br>{{ delivery_address.address2 }}',
                'billingText' => '{{ billing_address.name }}<br>{{ billing_address.address1 }}<br>{{ billing_address.address2 }}',
                'showOrderDate' => true,
                'orderDateTitle' => 'Next Order Date',
                'paymentTitle' => 'Payment Method',
                'footerText' => '<p>If you have any questions or need assistance, our support team is here to help. Just reply to this email or reach out at {{ merchant_support_email }}</p>',
            ],
        ],
        'subscription_payment_failure' => [
            'name' => 'Subscription Payment Failure',
            'type' => 'Payments',
            'icon' => 'credit-card-cancel',
            'description' => 'Sends when a subscription payment fails.',
            'enabled' => true,
            'subject' => 'Order payment failed for your subscription!',
            'body_html' => '<p>Hello {{ first_name }} {{ last_name }},</p><p>Automatic renewal for your subscription was unsuccessful.</p><p>Please update your payment details by clicking the "Manage Subscription" button below:</p>',
            'settings' => [
                'showBtn' => true,
                'btnText' => 'Manage Subscription',
                'fullWidth' => false,
                'showItems' => true,
                'qtyTitle' => 'Quantity',
                'showAddresses' => true,
                'shippingTitle' => 'Shipping Address',
                'billingTitle' => 'Billing Address',
                'shippingText' => '{{ shipping_title }}<br>{{ delivery_address.name }}<br>{{ delivery_address.address1 }}<br>{{ delivery_address.address2 }}',
                'billingText' => '{{ billing_address.name }}<br>{{ billing_address.address1 }}<br>{{ billing_address.address2 }}',
                'showOrderDate' => true,
                'orderDateTitle' => 'Next Order Date',
                'paymentTitle' => 'Payment Method',
                'footerText' => '<p>If you have any questions or need assistance, our support team is here to help. Just reply to this email or reach out at {{ merchant_support_email }}</p>',
            ],
        ],
        'upcoming_subscription_charge' => [
            'name' => 'Upcoming Subscription Charge',
            'type' => 'Payments',
            'icon' => 'email-newsletter',
            'description' => 'Sends an email before the upcoming order is charged.',
            'enabled' => true,
            'subject' => 'Your subscription order will be charged soon',
            'body_html' => '<p>Hello {{ first_name }} {{ last_name }},</p><p>Your upcoming subscription order will be charged soon.</p><p>You can make changes to this order before <b>{{ next_order_date }}</b>.</p><p>If you need to make changes (skip, update address, or payment), click the "Manage Subscription" button below:</p>',
            'settings' => [
                'days_before' => 1,
                'showBtn' => true,
                'btnText' => 'Manage Subscription',
                'fullWidth' => false,
                'showItems' => true,
                'qtyTitle' => 'Quantity',
                'showAddresses' => true,
                'shippingTitle' => 'Shipping Address',
                'billingTitle' => 'Billing Address',
                'shippingText' => '{{ shipping_title }}<br>{{ delivery_address.name }}<br>{{ delivery_address.address1 }}<br>{{ delivery_address.address2 }}',
                'billingText' => '{{ billing_address.name }}<br>{{ billing_address.address1 }}<br>{{ billing_address.address2 }}',
                'showOrderDate' => true,
                'orderDateTitle' => 'Next Order Date',
                'paymentTitle' => 'Payment Method',
                'footerText' => '<p>If you have any questions or need assistance, our support team is here to help. Just reply to this email or reach out at {{ merchant_support_email }}</p>',
            ],
        ],
        'subscription_payment_success' => [
            'name' => 'Subscription Payment Success',
            'type' => 'Payments',
            'icon' => 'email-newsletter',
            'description' => 'Sends when a subscription payment succeeds.',
            'enabled' => true,
            'subject' => 'Your subscription order is confirmed!',
            'body_html' => '<p>Hello {{ first_name }} {{ last_name }},</p><p>Your subscription has been successfully processed!</p><p>Here are the details of your order:</p>',
            'settings' => [
                'showBtn' => true,
                'btnText' => 'Manage Subscription',
                'fullWidth' => false,
                'showItems' => true,
                'qtyTitle' => 'Quantity',
                'showAddresses' => true,
                'shippingTitle' => 'Shipping Address',
                'billingTitle' => 'Billing Address',
                'shippingText' => '{{ shipping_title }}<br>{{ delivery_address.name }}<br>{{ delivery_address.address1 }}<br>{{ delivery_address.address2 }}',
                'billingText' => '{{ billing_address.name }}<br>{{ billing_address.address1 }}<br>{{ billing_address.address2 }}',
                'showOrderDate' => true,
                'orderDateTitle' => 'Next Order Date',
                'paymentTitle' => 'Payment Method',
                'footerText' => '<p>If you have any questions or need assistance, our support team is here to help. Just reply to this email or reach out at {{ merchant_support_email }}</p>',
            ],
        ],
        'out_of_stock_order' => [
            'name' => 'Out of Stock Order',
            'type' => 'Order management',
            'icon' => 'inventory',
            'description' => 'Sends when a subscription order cannot be processed because products are out of stock.',
            'enabled' => true,
            'subject' => 'Your subscription order could not be processed — items out of stock',
            'body_html' => '<p>Hello {{ first_name }} {{ last_name }},</p><p>We were unable to process your upcoming subscription order scheduled for <b>{{ order_date }}</b> because one or more items are currently out of stock.</p><p>You have not been charged for this order. We will try again on your next billing date, <b>{{ next_order_date }}</b>.</p><p>You can review your subscription and make changes using the button below:</p>',
            'settings' => [
                'showBtn' => true,
                'btnText' => 'Manage Subscription',
                'fullWidth' => false,
                'showItems' => true,
                'qtyTitle' => 'Quantity',
                'showAddresses' => true,
                'shippingTitle' => 'Shipping Address',
                'billingTitle' => 'Billing Address',
                'shippingText' => '{{ shipping_title }}<br>{{ delivery_address.name }}<br>{{ delivery_address.address1 }}<br>{{ delivery_address.address2 }}',
                'billingText' => '{{ billing_address.name }}<br>{{ billing_address.address1 }}<br>{{ billing_address.address2 }}',
                'showOrderDate' => true,
                'orderDateTitle' => 'Next Order Date',
                'paymentTitle' => 'Payment Method',
                'footerText' => '<p>If you have any questions or need assistance, our support team is here to help. Just reply to this email or reach out at {{ merchant_support_email }}</p>',
            ],
        ],
    ],
    'preview_sample' => [
        'first_name' => 'Jane',
        'last_name' => 'Doe',
        'order_date' => 'July 15, 2026',
        'next_order_date' => 'August 15, 2026',
        'merchant_support_email' => 'support@example.com',
        'shipping_title' => 'Standard Shipping',
        'payment_method' => 'Visa ending in 4242',
        'manage_subscription_url' => '#',
        'delivery_address' => [
            'name' => 'Jane Doe',
            'address1' => '123 Main Street',
            'address2' => 'Apt 4B',
        ],
        'billing_address' => [
            'name' => 'Jane Doe',
            'address1' => '123 Main Street',
            'address2' => 'Apt 4B',
        ],
        'line_items' => [
            ['title' => 'Gray hat (example)', 'quantity' => 1, 'price' => '$25.00'],
            ['title' => 'Black t-shirt (example)', 'quantity' => 2, 'price' => '$40.00'],
        ],
    ],
];
